### ISSUE TITLE
The osgQtQuick project source code does not contain license text

### ISSUE THREAD

**Issue by podsvirov** [podsvirov/osgqtquick#11]
I'm not well versed in licensing issues. The osgQtQuick project is developed on the basis of OpenSceneGraph and Qt projects.

It seems to me that LGPLv2.1 licensing is appropriate in the general case, but, maybe, there are exceptions.

I just want the project to be useful.

I will be grateful if someone will help me on this matter.

**Comment by podsvirov** [comment]
@pm-energid started this discussion on another #10 issue.

I propose to continue the discussion here.

Сс: @robertosfield

**Comment by pm-ur** [comment]
I agree that LGPL is quite appropriate for this library. However, with the missing license file, the users can easily miss/forget to display the license from this library. So, the license file should be included with the source code. Just add the license file to the develop branch. 
I'll send a pull request with the license file to help with that. :)

**Comment by pm-ur** [comment]
Just sent a pull request #12 for the license file commit

**Comment by podsvirov** [comment]
Closed by #12.
