### ISSUE TITLE
undeclared identifier 'loopType'

### ISSUE THREAD

**Issue by xuin-net** [podsvirov/osgqtquick#21]
when build in OSX it error with below log:
/Volumes/Work/OSG/osgqtquick-2.0.0.8/src/quick/window.cpp:62:13: error: use of
      undeclared identifier 'loopType'
            loopType = ThreadedRenderLoop;

It build success after replacing loopType with renderLoopType
is it a bug?

**Comment by podsvirov** [comment]
Hi @xuinvip, it's bug that fixed in 5c94c271ef7720a7a2f215bed3221fca57a5e440 by @pm-energid and available in `develop` branch.
In the near future I plan to add a new tag and you will be able to use it as well.
