### ISSUE TITLE
Failed to build because OSG 3.6.2 remove some of osgText::Font methods

### ISSUE THREAD

**Issue by tom-hnh** [podsvirov/osgqtquick#22]
Hello,

Since OSG 3.6.2 ([this commit](https://github.com/openscenegraph/OpenSceneGraph/commit/d2fa7c4317fc84da537f5c65c060ad0939d9e59f#diff-aceeb5cda74ca249057d9ce270591784)), the `osgText::Font`  does not contain methods `getGlyphImageMargin` and `setGlyphImageMargin` anymore.
They move theses methods to `osgText::Glyph` with : `setTexelMargin` and `getTexelMargin`. 

The building of  `osgqtquick` fails due to these changes.
Is it possible to fix this ? I tried myself but I was not able to understand how to deal with the new class `osgText::Glyph` which is used now.

Thanks for all your work :)

Regards,
Tom

**Comment by podsvirov** [comment]
Hello Tom! Thanks for your report.
I will try to sort this out, but it will take me some time.
I will report here as soon as I have news on this topic.

**Comment by podsvirov** [comment]
Hello @Tom-Henoch, please check latest code from `develop` branch.

**Comment by tom-hnh** [comment]
Hello !
Thanks it works !

But I have now another issue  see #23
