### ISSUE TITLE
how  can i get osgViewer ptr?

### ISSUE THREAD

**Issue by tileforge-dev** [podsvirov/osgqtquick#25]
i want use c++ code add some feature, in this way, it must get osgviewer pointer, how can i get it?

**Comment by podsvirov** [comment]
Try:
```cpp
osgQtQuick::Window::fromWindow(window)->viewer()
```
where `window` is pointer to your `QQuickWindow`.

**Comment by podsvirov** [comment]
Hello @ironjie, have you solved your problem?
